#!/bin/bash
# 110224
# add the hp4050 printer
/usr/sbin/lpadmin -p hp4050 -L "HP 4050" -E -v lpd://192.168.1.12 -P "/Library/Printers/PPDs/Contents/Resources/HP LaserJet 4050 Series.gz" -o printer-is-shared=false